In [1]:
import pandas as pd
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [7]:
df.shape

(891, 15)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [8]:
df["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [9]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [10]:
menn=df["age"].mean()

In [11]:
df["age"]=df["age"].fillna(menn)

In [12]:
df.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [13]:
df=df.drop(["embarked"],axis=1)
df.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [14]:
df=df.dropna()

In [15]:
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [16]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,First,woman,False,C,Southampton,yes,True

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 1 to 889
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     201 non-null    int64
 1   pclass       201 non-null    int64
 2   sex          201 non-null    object
 3   age          201 non-null    float64
 4   sibsp        201 non-null    int64
 5   parch        201 non-null    int64
 6   fare         201 non-null    float64
 7   class        201 non-null    category
 8   who          201 non-null    object
 9   adult_male   201 non-null    bool
 10  deck         201 non-null    category
 11  embark_town  201 non-null    object
 12  alive        201 non-null    object
 13  alone        201 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(4)
memory usage: 18.5+ KB

In [18]:
df.shape

(201, 14)

In [19]:
df["alone"]=df["alone"].astype("int64")
df["adult_male"]=df["adult_male"].astype("int64")

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 1 to 889
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     201 non-null    int64
 1   pclass       201 non-null    int64
 2   sex          201 non-null    object
 3   age          201 non-null    float64
 4   sibsp        201 non-null    int64
 5   parch        201 non-null    int64
 6   fare         201 non-null    float64
 7   class        201 non-null    category
 8   who          201 non-null    object
 9   adult_male   201 non-null    int64
 10  deck         201 non-null    category
 11  embark_town  201 non-null    object
 12  alive        201 non-null    object
 13  alone        201 non-null    int64
dtypes: category(2), float64(2), int64(6), object(4)
memory usage: 21.3+ KB

In [21]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols_to_encode = ['sex', 'who', 'embark_town', 'alive', 'class', 'deck']

for col in cols_to_encode:
    df[col] = le.fit_transform(df[col])

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 1 to 889
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     201 non-null    int64
 1   pclass       201 non-null    int64
 2   sex          201 non-null    int64
 3   age          201 non-null    float64
 4   sibsp        201 non-null    int64
 5   parch        201 non-null    int64
 6   fare         201 non-null    float64
 7   class        201 non-null    int64
 8   who          201 non-null    int64
 9   adult_male   201 non-null    int64
 10  deck         201 non-null    int64
 11  embark_town  201 non-null    int64
 12  alive        201 non-null    int64
 13  alone        201 non-null    int64
dtypes: float64(2), int64(12)
memory usage: 23.6 KB

In [23]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,0,38.0,1,0,71.2833,0,2,0,2,0,1,0
3,1,1,0,35.0,1,0,53.1000,0,2,0,2,2,1,0
6,0,1,1,54.0,0,0,51.8625,0,1,1,4,2,0,1
10,1,3,0,4.0,1,1,16.7000,2,0,0,6,2,1,0
11,1,1,0,58.0,0,0,26.5500,0,2,0,2,2,1,1

In [24]:
x = df.drop(["survived"],axis=1)
y = df[["survived"]]

In [25]:
y.head()

    survived
1          1
3          1
6          0
10         1
11         1

In [26]:
x.head()

,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
1,1,0,38.0,1,0,71.2833,0,2,0,2,0,1,0
3,1,0,35.0,1,0,53.1000,0,2,0,2,2,1,0
6,1,1,54.0,0,0,51.8625,0,1,1,4,2,0,1
10,3,0,4.0,1,1,16.7000,2,0,0,6,2,1,0
11,1,0,58.0,0,0,26.5500,0,2,0,2,2,1,1

In [27]:
xtrain,xtest, ytrain,ytest= train_test_split(x,y, test_size=0.10)

In [28]:
dt = DecisionTreeClassifier()

In [29]:
model = dt.fit(xtrain,ytrain)
model.score(xtrain,ytrain)

1.0

In [30]:
model.score(xtest,ytest)

1.0

In [31]:
xtest.head()

,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
139,1,1,24.000000,0,0,79.20,0,1,1,1,0,0,1
632,1,1,32.000000,0,0,30.50,0,1,1,1,0,1,1
776,3,1,29.699118,0,0,7.75,2,1,1,5,1,0,1
356,1,0,22.000000,0,1,55.00,0,2,0,4,2,1,0
520,1,0,30.000000,0,0,93.50,0,2,0,1,2,1,1

In [32]:
ytest.head()

     survived
139         0
632         1
776         0
356         1
520         1

In [34]:
pred = model.predict([ [1, 1, 32.000000, 0, 0, 30.50, 0, 1, 1, 1, 0, 1, 1] ])
pred

c:\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [36]:
pred1=model.predict(xtest)
pred1

array([0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1])

In [37]:
import pickle
pickle.dump(model,open("titanic.pkl","wb"))